### ISSUE TITLE
module MimetypeParser is not available in built release

### ISSUE THREAD

**Issue by d4rk5eed** [NobbZ/file_info#6]
```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function MimetypeParser.parse!/1 is undefined (module MimetypeParser is not available)
        MimetypeParser.parse!("image/png")
        (file_info) lib/file_info/mime.ex:16: FileInfo.Mime.parse!/1
        (file_info) lib/file_info.ex:25: FileInfo.to_tuple/1
        (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
        (elixir) lib/enum.ex:3080: Enumerable.List.reduce/3
        (elixir) lib/stream.ex:1403: Enumerable.Stream.do_each/4
        (elixir) lib/enum.ex:1767: Enum.reverse/2
        (elixir) lib/enum.ex:2528: Enum.to_list/1

```

problem was fixed by explicit declaration of mimetype_parser dep in mix.exs, but it is not obviosly good

**Comment by NobbZ** [comment]
Yeah, I have an idea, will take a look when I have a linux machine at hands (in about 8 to 10 hours)

**Comment by mtarnovan** [comment]
It's missing from the app list: https://github.com/NobbZ/file_info/blob/master/mix.exs#L25

It will be picked up locally through deps, but when building a release deps are taken from app list and it will be missing.
